### PR TITLE
Automatic navigation to appropriate Run tabs

### LINKED ISSUE #505: "View" link should take user to metadata tab if not running
When clicking the "View" link on a tale that isn't running, I expect to be taken to the metadata tab. This way, I can learn about the tale before running it.  If the tale is already started, I expect to be taken to the interact tab.

### LINKED ISSUE #506: Disable interact tab when not running
For discussion:

This is in the newer round of mockups:
http://www.crc.nd.edu/~kfurse/wholetale-css-mock-up-sui_s2019/run-meta-pre-run.html

It makes sense to not allow access to Interact unless the tale is running.  This does require the user to understand that they need to select "Run"  first.  We could possibly add a tooltip on the disabled tab or even add a dialog if they click it "Do you want to run this?"

### LINKED ISSUE #507: Run from browse should take me to the Run > Interact page
If I select "Run" on a tale on the Browse page, I expect to be taken to the Run > Interact page.

### LINKED ISSUE #508: Compose should take me immediately to Run > Interact
The composing and launching a tale, I expect to be taken to the Run > Interact page to wait for the instance to start up.

### PR DESCRIPTION
**Pull request by bodom0015**
### Problem
Under certain conditions, the user doesn't necessarily know where they should go next.

Fixes #508 
Fixes #507 
Fixes #506 
Fixes #505 

### Approach
Help "guide" the user to where we think they want to go:
* Disable the "Run > Interact" tab when the Tale is not running
* When a user creates a new Tale from the Browse view, they are taken to the "Run > Interact" tab if the user chose to Start the Tale or "Run > Metadata" if they chose not to start it
* When a user clicks "Run" from the Browse view, they are taken to the "Run > Interact" tab for the now launching Tale
* When a user clicks "View" from the Browse view, they are taken to the "Run > Interact" tab if a Tale instance exists, or to "Run > Metadata" tab for a stopped Tale
* When a user clicks "Run" from the Run view, they are taken to the "Run > Interact" tab for the now launching Tale

### How to Test
Prerequisite: At least one stopped Tale, at least one Tale you don't own

1. Checkout and run this branch locally, rebuild the dashboard
2. Login to the WholeTale Dashboard
3. Navigate to the Browse view and choose a stopped Tale
4. Browse->Metadata 1: Create Tale" (without launching) from Create Tale modal
   * You should be brought to the "Run > Metadata" view for this Tale (#508)
   * You should see that the "Run > Interact" tab is disabled (#506)
5. Browse->Metadata 2: Hover over the Tale image and click the "View" button that appears on hover
   * You should be brought to the "Run > Metadata" view for this Tale (#505)
   * You should see that the "Run > Interact" tab is disabled (#506)
6. Browse->Interact 1: "Create Tale And Launch" from Create Tale modal
   * You should be brought to the "Run > Metadata" view for this Tale (#508)
   * You should see that the "Run > Interact" tab is disabled (#506)
7. Browse->Interact 2: Go back to the Browse view and click the "Run" button beneath a stopped Tale
    * You should be brought immediately to the "Run > Interact" view (#507)
    * You should see that the Interact tab is now enabled (#506)
    * You should see the status message(s) indicating that your Tale is now launching
8. Browse->Interact 3: Hover over the now-launching Tale's image and click the "View" button that appears on hover
    * You should be brought immediately to the "Run > Interact" view (#507)
    * You should see that the Interact tab is now enabled (#506)
    * You should see the status message(s) indicating that your Tale is now launching
9. On the "Run > Interact" view, wait for the Tale ot start and then click the "Stop" button to stop it again
    * You should see that the Interact tab is now disabled
10. Run->Interact: Navigate to the "Run > Metadata" view for the now stopped Tale and click "Run"
    * You should be brought immediately to the "Run > Interact" view 
    * You should see that the Interact tab is now enabled (#506)
    * You should see the status message(s) indicating that your Tale is now launching
11. Browse->Interact 4 (w/ COL): Go back to the Browse view again and click the "Run" button beneath a Tale you do not own
    * You should be prompted by a modal asking you to "Copy and Run"
12. Confirm by clicking "Copy and Run"
    * The modal should close
    * You should be brought immediately to the "Run > Interact" view (#507)
    * You should see that the Interact tab is enabled (#506)
    * You should see the status message(s) indicating that your Tale is now launching

### CODE REVIEW

**Comment by craig-willis** [comment]
This is great -- I didn't think you'd get to these.

I ran into the same error reported in https://github.com/whole-tale/dashboard/pull/514#issuecomment-514311641 until I rebased against master.  After rebasing, I'm seeing an error when hitting "Run" from the browse page.

Screen Shot 2019-07-24 at 9 43 51 AM

Also, https://github.com/whole-tale/dashboard/issues/505 suggests displaying the metadata tab if the tale isn't running and the interact tab if it is. With this PR, the metadata tab is displayed regardless.  Was this intentional?

**Comment by bodom0015** [comment]
@craig-willis good point, I apparently hadn't read that ticket very carefully...

Updated this PR with https://github.com/whole-tale/dashboard/pull/517/commits/6b43b37a3367101ed2ca88dc32c01c29e510b969 to change the "View" button to pass different queryParams based on if an instance exists

Also added simple/lazy handling for #508 in https://github.com/whole-tale/dashboard/pull/517/commits/6f21b18b54f76103f1e03c42caab76d16f682d72, since the Create Tale modal was finally merged

**Comment by craig-willis** [comment]
Thanks, @bodom0015. This is looking great.

For no. 6 ("Browse -> Interact 1: Create and Launch tale"): if I have 2 instances running already, I don't see the error and am taken to the metadata tab. As I recall, this was one of your original concerns since the error handling was on the browse page.

If I return to the Browse page after this, I get a large number of console errors "Cannot read property 'replace' of undefined":

Screen Shot 2019-07-25 at 9 57 29 AM

**Comment by Xarthisius** [comment]
I ran into troubles in 3:

```
"Error: Assertion Failed: You modified "transitioningIn" twice on <wholetale@component:link-to::ember466> in a single render. It was rendered in "component:link-to" and modified in "component:ui/tale-tabs-selector". This was unreliable and slow in Ember 1.x and is no longer supported. See https://github.com/emberjs/ember.js/issues/13948 for more details.
    at new EmberError (https://dashboard.local.wholetale.org/assets/vendor.js:29038:25)
    at Object.assert (https://dashboard.local.wholetale.org/assets/vendor.js:29288:15)
    at TransactionRunner.assertNotRendered (https://dashboard.local.wholetale.org/assets/vendor.js:39298:42)
    at notifyPropertyChange (https://dashboard.local.wholetale.org/assets/vendor.js:39582:15)
    at https://dashboard.local.wholetale.org/assets/vendor.js:39631:7
    at Meta._forEachIn (https://dashboard.local.wholetale.org/assets/vendor.js:40919:11)
    at Meta.forEachInDeps (https://dashboard.local.wholetale.org/assets/vendor.js:40892:19)
    at iterDeps (https://dashboard.local.wholetale.org/assets/vendor.js:39620:13)
    at dependentKeysDidChange (https://dashboard.local.wholetale.org/assets/vendor.js:39600:5)
    at notifyPropertyChange (https://dashboard.local.wholetale.org/assets/vendor.js:39565:7)"
```

### Steps to reproduce

1. Checkout and run this branch locally, rebuild the dashboard
1. Register LIGO Tale.
1. Login to dashboard.
1. Create a Tale without launching (Browse > Create New... > Create New Tale) Note: this will redirect you to metadata page of the new Tale
1. Click < Return to Dashboard
1. Hover over Ligo Tale and click "View"

**Comment by bodom0015** [comment]
@craig-willis Good catch on that stacktrace... I'm not sure what's calling the `waitFor` there, but we're apparently passing it something invalid somewhere. Adding a null-check to the `waitFor` prevents that loop/errors from occurring.

@Xarthisius following your steps, things seem to work as expected and I don't see the error you described (see http://recordit.co/HVXStrwWHX). Has the LIGO Tale changed recently? Do I perhaps need to delete it and recreate this Tale or something?

**Comment by bodom0015** [comment]
Me:
> I can try to debounce these navigations, since apparently chaining them can be bad under certain circumstances.

I pushed this change.. if you can reliably recreate this issue, please let me know if this might fix it? 😄

**Comment by Xarthisius** [comment]
The missing piece in reproducing that Ember error was "development" mode. I was trying to be a good citizen and provide meaningful tracebacks. I doesn't occur in "production". I'll check your latest commit in a sec.

**Comment by Xarthisius** [comment]
It's still there, but let's ignore it since it's not happening with the settings we normally use.

**Comment by bodom0015** [comment]
@Xarthisius ahhh, so that's one of those odd little messages that get suppressed in prod mode...

Regarding dev mode: early on in the project I was running in development mode, but the styles were ever-so-slightly different from production, and I could never figure out why this was happening. I've used prod mode since then to make sure that what I code is what actually runs after being deployed.

On rare occasions when things are being really weird or slow I try dev mode again, but hadn't thought to do so here.

Thank you, @Xarthisius! 😄

**Comment by bodom0015** [comment]
Amended https://github.com/whole-tale/dashboard/pull/517/commits/d9c635434b46bf85262623105ad871061abc1666 with the correct fix. I had accidentally put the `later()` on the wrong line.

Stack trace no longer appears for me after debouncing this second navigation.

**Comment by bodom0015** [comment]
@craig-willis @Xarthisius I've pushed some changes to show an error modal as Craig had suggested... let me know how we feel about this as a potential solution.

The flow for the user is now as follows:
`Browse > Create New Tale... Create Tale Modal > Create Tale and Launch > Error modal > Close modal > Run/Metadata

**Comment by craig-willis** [comment]
Thanks @bodom0015 -- I like this flow (obviously).   As discussed on Slack, some of the other "too many instances" handling is no longer working as expected: 

With two instances running:

1. Selecting "Run" from the Browse page:  the error appears in the console and I am not navigated to the run page (stays on browse)
2. Selecting "Run" from the Run page: the Run icon changes (!) but no error is displayed. As you noted, this was on the interact tab which is now disabled.

I don't know how best to handle this under the new navigation scheme -- and again acknowledge that this was one of the reasons you were concerned about the change.  

I can think of a few options:
* For 1, either a) display the error on the card and don't navigate as before; or b) navigate to the run page but somehow the run page would need to display the error.
* For 2, either a) display an error similar to the new create flow or b) enable interact and display as before

I'm sure you'll have better ideas?

**Comment by bodom0015** [comment]
@craig-willis I have attempted to quickly address both of these issues:
1. Added a [Negative Message](https://semantic-ui.com/collections/message.html#negative--error) to the Browse view and prevent navigation when a launch error is hit
2. Added an [Inverted Tooltip](https://semantic-ui.com/modules/popup.html#tooltip) to the Run button on the Run view when in the error state (we were already detecting this state to apply the (!) icon)

**Comment by craig-willis** [comment]
Thanks, @bodom0015. This looks good to me.

I happened to be testing this with https://github.com/whole-tale/gwvolman/pull/82 and ran into https://github.com/whole-tale/dashboard/issues/523 and https://github.com/whole-tale/dashboard/issues/524.   I'm inclined to approve/merge this one and address the new issues separately.

**Pull request merged**
