### PR TITLE
Update Manage > Data and Select Data modal to use /datasets endpoint

### LINKED ISSUE #357: Update Manage > Data and Select Data modal to use dataset endpoint
Relates to https://github.com/whole-tale/girder_wholetale/pull/205 and #354.

**Current behavior:**
* Select Manage > Data displays the list of datasets the user has registered.
* Assuming #354 is fixed, Select Data modal displays list of datasets in the WT catalog (global) using the "Whole Tale Catalog folder"

Per the [mockups](http://www.crc.nd.edu/~kfurse/wholetale-css-mock-up-sui_f2018/browse-catalog.html) we will eventually move to the Data Catalog page that lists all registered datasets and can be filtered by only my registered datasets

**Desired behavior:**
* To make incremental progress toward the mockup without major UI refactoring, the Manage > Data tab should display catalog entries based on the `/datasets` endpoint ~~with the option to filter by myData~~. 
* Additionally, the Select Data modal "WT Catalog" tab should use the /datasets endpoint and have option to filter by myData.

**Basic flow:**
* User selects Manage > Data
* User registers a dataset
* Dataset appears in Manage > Data (based on /datasets endpoint) ~~and can filter by myData~~
* User can browse into folders, but no longer move, copy or rename. 
* User can remove the dataset, but only at the root (not items within the dataset)
* User can download items
* User selects "Select Data" modal from external_data tab, sees the same datasets in WT Catalog and can filter by myData.

Note that we will eventually remove the Manage Tab to be replaced by something like the [Data Catalog](http://www.crc.nd.edu/~kfurse/wholetale-css-mock-up-sui_f2018/browse-catalog.html) mockup.

### PR DESCRIPTION
**Pull request by bodom0015**
* Fixes #357

## How to Test
1. Sync your girder_wholetale with master, checkout and run this dashboard branch locally, and rebuild the dashboard
2. Login to the WholeTale Dashboard
3. Create and Launch a Tale, if you haven't already
4. Register a new Dataset - this is important with the addition of https://github.com/whole-tale/girder_wholetale/pull/205
5. Navigate to the Run view by clicking a "Launched Tale" in the panel on the right
6. Click the "Files" tab beneath the Tale header
    * You should be presented with a directory-browser with some navs on the left side
7. On the left, choose the "External Data" nav
    * You should be presented with a list containing any "External Data" added to this tale
8. Click the (+) button at the top-right
    * You should be presented with the "Select Data" modal
    * The "WholeTale Catalog" nav on the left should be selected by default - the modal should list the full contents of the WholeTale Catalog (GET `/dataset`) in the left pane
    * You should now see an option for "My Data" in the navs on the left
    * Full datasets should be selectable in the same way as the folders and files beneath them
9. Click the "My Data" nav on the left
    * The view should filter to show only those datasets that the currently logged-in user registered
10. On the top navbar, click "Manage"
    * You should be presented with a directory-browser with some navs on the left side
11. On the left, choose the "Data" nav
    * You should be presented with a list containing only the datasets in the WholeTale Catalog that the user has registered
12. Click on a dataset
    * You should be shown the contents of that dataset
    * If loading takes too long, you should see a loading spinner appear in the directory-browser, indicating that the clicked folder contents are loading
13. Click the dropdown arrow to the right of a file or folder
    * You should see only an option for "Download"
14. Click the breadcrumb "Data"
    * You should be brought back to the top-level list of the user's registered datasets
15. Click the dropdown arrow to the right of a dataset
    * You should see an option for "Download"
    * You should see an option for "Remove" - NOTE: since there is currently no `DELETE /datasets/:id` endpoint, this is not yet functional

### CODE REVIEW

**Comment by bodom0015** [comment]
Already noticed a few issues that I need to looking into:
* Manage > Data shows "Invalid date" for `dataset.updated`
* Missing the filter(s) for `myData=true`

**Comment by Xarthisius** [comment]
@bodom0015 looks great! I found one issue: `GET /dataset` can return both folder and items (as indicated by `modelType`). Currently in the root of Manage > Data everything is interpreted as a folder.

**Comment by bodom0015** [comment]
Good catch! I hadn't thought of the item case (all of my test datasets are folders, it seems)..

I will look into that case too, thanks! :)

**Comment by Xarthisius** [comment]
> Good catch! I hadn't thought of the item case (all of my test datasets are folders, it seems)..
> 
> I will look into that case too, thanks! :)

It might be useful to review and merge this: https://github.com/whole-tale/girder_wholetale/pull/234 :)

**Comment by bodom0015** [comment]
Synced this branch with the changes in https://github.com/whole-tale/girder_wholetale/pull/234

Also handled "item" datasets on the Manage > Data view and disabled the "Remove" button there (there is currently no `DELETE /dataset` endpoint)

Is there an open PR for filtering on myData somewhere? I don't see any params on the SwaggerUI page on either local or dev that might correspond to this

**Comment by bodom0015** [comment]
Updated this PR to handle the `myData` filtering, as requested:
* Manage > Data always assumes that `myData=true`
* Run > Files > External Data > Select Data modal now offers `My Data` as an option

**Comment by Xarthisius** [comment]
@bodom0015 I still get the "item-as-folder" issue in Select Data modal. It works fine in Manage > Data.

**Comment by bodom0015** [comment]
@Xarthisius Sorry about that, I could've sworn I swapped that icon.. I think I've fixed this now

**Pull request merged**
